# Generated by Django 2.2 on 2022-09-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userregistrationmodel',
            table='UserRegistrationsModel',
        ),
    ]
